package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"dashboard-bl/graph/model"
	"fmt"
)

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context, filter *model.ClientFilterInput) (*model.ClientList, error) {
	panic(fmt.Errorf("not implemented: Clients - clients"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
