// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Client struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Inn         string        `json:"inn"`
	Email       string        `json:"email"`
	IsKik       bool          `json:"isKik"`
	IsPaymaster bool          `json:"isPaymaster"`
	CreatedAt   time.Time     `json:"createdAt"`
	UpdatedAt   time.Time     `json:"updatedAt"`
	Details     *ClientDetail `json:"details,omitempty"`
	Services    []*Service    `json:"services"`
}

type ClientDetail struct {
	FullName     *string `json:"fullName,omitempty"`
	Director     *string `json:"director,omitempty"`
	Kpp          *string `json:"kpp,omitempty"`
	Ogrn         *string `json:"ogrn,omitempty"`
	LegalAddress *string `json:"legalAddress,omitempty"`
	PostAddress  *string `json:"postAddress,omitempty"`
	Bank         *string `json:"bank,omitempty"`
	Bik          *string `json:"bik,omitempty"`
	CorrAcc      *string `json:"corrAcc,omitempty"`
	CalcAcc      *string `json:"calcAcc,omitempty"`
}

type ClientFilterInput struct {
	Name     *string   `json:"name,omitempty"`
	Inn      *string   `json:"inn,omitempty"`
	Email    *string   `json:"email,omitempty"`
	IsKik    *bool     `json:"isKik,omitempty"`
	SortBy   *string   `json:"sortBy,omitempty"`
	Include  []*string `json:"include,omitempty"`
	Page     *int32    `json:"page,omitempty"`
	PageSize *int32    `json:"pageSize,omitempty"`
}

type ClientList struct {
	Items []*Client `json:"items"`
	Total int32     `json:"total"`
}

type Query struct {
}

type Service struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	MonthlyCost float64   `json:"monthlyCost"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}
