// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewClientDetailInput struct {
	FullName     *string `json:"full_name,omitempty"`
	Director     *string `json:"director,omitempty"`
	Kpp          *string `json:"kpp,omitempty"`
	Ogrn         *string `json:"ogrn,omitempty"`
	LegalAddress *string `json:"legal_address,omitempty"`
	PostAddress  *string `json:"post_address,omitempty"`
	Bank         *string `json:"bank,omitempty"`
	Bik          *string `json:"bik,omitempty"`
	CorrAcc      *string `json:"corr_acc,omitempty"`
	CalcAcc      *string `json:"calc_acc,omitempty"`
}

type NewClientInput struct {
	Name        string                `json:"name"`
	Inn         string                `json:"inn"`
	Email       string                `json:"email"`
	IsKik       *bool                 `json:"is_kik,omitempty"`
	IsPaymaster *bool                 `json:"is_paymaster,omitempty"`
	Details     *NewClientDetailInput `json:"details,omitempty"`
	ServiceIds  []int32               `json:"service_ids,omitempty"`
}

type NewDocumentInput struct {
	ClientID     int32  `json:"client_id"`
	PDF          string `json:"pdf"`
	DocumentType string `json:"document_type"`
}

type NewServiceInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	MonthlyCost float64 `json:"monthly_cost"`
}

type Query struct {
}

type UpdateClientDetailInput struct {
	FullName     *string `json:"full_name,omitempty"`
	Director     *string `json:"director,omitempty"`
	Kpp          *string `json:"kpp,omitempty"`
	Ogrn         *string `json:"ogrn,omitempty"`
	LegalAddress *string `json:"legal_address,omitempty"`
	PostAddress  *string `json:"post_address,omitempty"`
	Bank         *string `json:"bank,omitempty"`
	Bik          *string `json:"bik,omitempty"`
	CorrAcc      *string `json:"corr_acc,omitempty"`
	CalcAcc      *string `json:"calc_acc,omitempty"`
}

type UpdateClientInput struct {
	ID          int32                    `json:"id"`
	Name        *string                  `json:"name,omitempty"`
	Inn         *string                  `json:"inn,omitempty"`
	Email       *string                  `json:"email,omitempty"`
	IsKik       *bool                    `json:"is_kik,omitempty"`
	IsPaymaster *bool                    `json:"is_paymaster,omitempty"`
	Details     *UpdateClientDetailInput `json:"details,omitempty"`
	ServiceIds  []int32                  `json:"service_ids,omitempty"`
}

type UpdateServiceInput struct {
	ID          int32    `json:"id"`
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	MonthlyCost *float64 `json:"monthly_cost,omitempty"`
}
